version: '3.8' 

services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cy200619...
      MYSQL_DATABASE: demo1       # 可选，初始化时自动建库
      MYSQL_USER: root            # 可选，初始化时建用户
      MYSQL_PASSWORD: Cy200619...     # 可选
    volumes:
      - ./mysql_data:/var/lib/mysql  # 本地挂载，避免匿名卷
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
