export enum ConfigEnum {
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
}

export enum LogEnum {
  LOG_ON = 'LOG_ON',
  LOG_LEVEL = 'LOG_LEVEL',
}
